### ISSUE TITLE
Is it posible to control fan speed depend on two temp sensors? 

### ISSUE THREAD

**Issue by stalkerg** [markusressel/fan2go#144]
Subj. 
Very often my CPU is cold, and GPU is hot, but only my water cool system sucks fresh air into the case.
If GPU has a high temp my water cool fans also should increase speeds. Basically, it's should calculate separately, but the final speed should be a max of this two.

**Comment by nawuko** [comment]
You can create a custom curve for that, i have the same scenario as you and use a custom curve.

modified readme example:

```yaml
curves:
  - id: case_avg_curve
    function:
      # Type of aggregation function to use, one of: minimum | maximum | average | delta
      type: maximum
      # A list of curve IDs to use
      curves:
        - cpu_curve
        - gpu_curve
```
