### ISSUE TITLE
Dell Server - Cycles without Settling

### ISSUE THREAD

**Issue by tjbennett** [markusressel/fan2go#201]
**Describe the bug**
Dell Server 3930 - has 3 fans all of which can be controlled by a temperature sensor (or many sensors). Attempting to replace fancontrol with an easier, smoother method. 

Install fan2go and tried to build a yaml file to represent server conditions

Use a definition of single cpu fan and representative sensor (cpu temp sensor). 

In Dell 3930, /sys/class/hwmon/hwmon3/pwm1 represents as 128 even when in slow cycles. Therefore reading back a PWM setting is fraught with issues. A PWM setting should represent an RPM value and instead of reading back the PWM settings a relation to the RPM would be more representative of the PWM setting.

**To Reproduce**

Install fan2go, using go 1.20, and set yaml as following:

``` yaml
dbPath: "/etc/fan2go/fan2go.db"

runFanInitializationInParallel: false
maxRpmDiffForSettledFan: 250

tempSensorPollingRate: 2000ms
tempRollingWindowSize: 10

rpmPollingRate: 1s
rpmRollingWindowSize: 10

controllerAdjustmentTickRate: 200ms

fans:
  - id: cpu
    hwmon:
      platform: dell_smm-virtual-0
      index: 1
    neverStop: true
    curve: cpu_curve
    minPwm: 128
    startPwm: 128
    maxPwm: 255
    pwmMap:
      0 : 128
      170: 138
      255: 255

  - id: pcie
    hwmon:
      platform: dell_smm-virtual-0
      index: 2
    neverStop: true
    curve: pcie_curve
    minPwm: 128
    startPwm: 128
    maxPwm: 255
    pwmMap:
      0 : 128
      170: 138
      255: 255

  - id: psup
    hwmon:
      platform: dell_smm-virtual-0
      index: 3
    neverStop: true
    curve: psup_curve
    minPwm: 128
    startPwm: 128
    maxPwm: 255
    pwmMap:
      0 : 128
      170: 138
      255: 255

sensors:
  - id: cpu_package
    hwmon:
      platform: dell_smm-virtual-0
      index: 1


curves:
  - id: cpu_curve
    linear:
      sensor: cpu_package
      steps:
        - 40: 128
        - 50: 150
        - 80: 255

  - id: pcie_curve
    linear:
      sensor: cpu_package
      steps:
        - 40: 128
        - 50: 150
        - 80: 255

  - id: psup_curve
    linear:
      sensor: cpu_package
      steps:
        - 40: 128
        - 50: 150
        - 80: 255

  - id: case_avg_curve
    function:
      type: average
      curves:
        - cpu_curve
        - pcie_curve
        - psup_curve
```
1. Start fan2go - in this instance used superuser "# go run main.go -c "fan2go.yaml""
2. Observe system fail as writing "0" to pwm does not result in pwm reading as "0"
3. Remove the check on matching values and get the system building the curve information
4. Once that is done, let the system run. It will go high (RPM set to 255) then drop to low (128) in a cyclic manner, not in any way related to the temp sensor
5.  Run "stress --cpu 6" temperature rises and system does not adjust to cool system

**Expected behavior**
Expect the system to ramp up fan speed when temperature increases, slowly ramp fan system down as system cools.

**Desktop (please complete the following information):**

- Distro: Ubuntu 20.04 server version
- `uname -a`: Linux SG30d042e20c0a 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- `sensors -v`: sensors version 3.6.0 with libsensors version 3.6.0
- `fan2go version`: (dev) b3f19b3014429b32d658d7356381e641091ff651

**Additional context**
There may be a great misunderstanding of the configuration or the intent of this program that has created this report.

7.

**Comment by markusressel** [comment]
Hey @tjbennett thx for the report :rocket: 

FYI: For better readability, I have removed the comments from your configuration.

> Observe system fail as writing "0" to pwm does not result in pwm reading as "0"
fan2go should not fail because of this, it should issue warnings about it though.

> Remove the check on matching values and get the system building the curve information
If you set `minPwm` and `maxPwm`, building the curve is (currently) without use, since the curve is only used to determine these values. If they are already set in the config, the curve is not build because it is not necessary.

> Once that is done, let the system run. It will go high (RPM set to 255) then drop to low (128) in a cyclic manner, not in any way related to the temp sensor

You specify a custom `pwmMap` definition for all of your fans:

```yaml
  minPwm: 128
  startPwm: 128
  maxPwm: 255
  pwmMap:
    0 : 128
    170: 138
    255: 255
```

How did you get to these values? Are there no possible PWM values other than the three you have specified?

Setting a `minPwm` of `128` in combination with the given `pwmMap` will result in the fan always beeing set to at least `170`, which will be mapped to a PWM value of `138` due to your config. There might be a misunderstanding in how the `pwmMap` config option works. Check out #161 (caution, very long thread) to get a more in-depth understanding of what the `pwmMap` config option is doing.

Increasing the value of `tempSensorPollingRate` to a 10 times greater value than default might also play into this. Can you test if reverting this to the default `200ms` fixes the cycling?
