### ISSUE TITLE
Unable to set fan mode/Dell XPS 7390/`dell_smm`/`pwm1_enable`

### ISSUE THREAD

**Issue by piyueh** [markusressel/fan2go#229]
**Describe the bug**

`fan2go fan init -i <fan>` and `fan2go` gave errors complaining being unable to set fan mode through `pwm*_enable`.

**To Reproduce**
1. `$ fan2go detect` (I'm only posting relevant sections here):
   <details>
   <summary>Click me to expand</summary>
   
   ```shell
   > dell_smm-isa-0000
     Fans     Index  Channel  Label        RPM  PWM  Auto 
     -----------------------------------------------------
              1      1        hwmon4/fan1  0    0    false
              2      2        hwmon4/fan2  0    0    false
     Sensors  Index  Label                       Value
     -------------------------------------------------
              1      hwmon4/temp1 (temp1_input)  44000
              2      hwmon4/temp2 (temp2_input)  37000
              3      hwmon4/temp3 (temp3_input)  38000
              4      hwmon4/temp4 (temp4_input)  32000
              5      hwmon4/temp5 (temp5_input)  38000
              6      hwmon4/temp6 (temp6_input)  38000
              7      hwmon4/temp7 (temp7_input)  37000
   
   > coretemp-isa-0000
     Sensors  Index  Label                       Value
     -------------------------------------------------
              1      Package id 0 (temp1_input)  53000
              2      Core 0 (temp2_input)        51000
              3      Core 1 (temp3_input)        51000
              4      Core 2 (temp4_input)        52000
              5      Core 3 (temp5_input)        50000
              6      Core 4 (temp6_input)        52000
              7      Core 5 (temp7_input)        48000
   ```
   </details>

2. `$ cat /etc/fan2go/fan2go.yaml`:
   <details>
   <summary>Click me to expand</summary>
   
   ```yaml
   fans:
     - id: fan-1
       hwmon:
         platform: dell_smm-isa-0000
         rpmChannel: 1
         pwmChannel: 1
         index: 0
       neverStop: true
       curve: fan-curve-1
   sensors:
     - id: cpu-package
       hwmon:
         platform: coretemp-isa-0000
         index: 1
   curves:
     - id: fan-curve-1
       linear:
         sensor: cpu-package
         min: 50
         max: 90
   ```
   </details>
3. `# fan2go fan init -i fan-1`, I got
   <details>
   <summary>Click me to expand</summary>
   
   ```shell
   INFO  Using configuration file at: /etc/fan2go/fan2go.yaml
   INFO  Using persistence at: /etc/fan2go/fan2go.db
   INFO  Deleting existing data for fan 'fan-1'...
   INFO  Computing pwm map...
   ERROR   Unable to set Fan Mode of 'fan-1' to "1": PWM mode stuck to -1
   ERROR   Unable to set Fan Mode of 'fan-1' to "0": write
       /sys/devices/platform/dell_smm_hwmon/hwmon/hwmon5/pwm1_enable:
       invalid argument
   INFO  Measuring RPM curve...
   ERROR   Unable to set Fan Mode of 'fan-1' to "1": PWM mode stuck to -1
   ERROR   Unable to set Fan Mode of 'fan-1' to "0": write
       /sys/devices/platform/dell_smm_hwmon/hwmon/hwmon5/pwm1_enable:
       invalid argument
   WARNING  Could not enable manual fan mode on fan-1, trying to
       continue anyway...
   SUCCESS  Done!
   INFO  Using configuration file at: /etc/fan2go/fan2go.yaml
   fan-1
   ------------
   Min PWM    0
   Start PWM  0
   Max PWM    0
   ```
   </details>

**Expected behavior**

No error messages.

**Desktop (please complete the following information):**

- Laptop model: Dell XPS 7390
- Distro: Arch Linux
- `uname -a`: 6.3.2-arch1-1
- `sensors -v`: sensors version 3.6.0+git with libsensors version 3.6.0+git
- `fan2go version`: commit c20619ea88909b5adcaf0ee8084929ef60f6b8d3

**Additional context**

According to `hwmon`'s documentation, for `dell_smm`, the file `pwm1_enable` does not accept `0`. A value of `1` to `pwm1_enable` means disabling the automatic BIOS fan control, while `2` means enabling such automatic control. See [here](https://www.kernel.org/doc/Documentation/hwmon/dell-smm-hwmon.rst).
