### ISSUE TITLE
Help needed with sensor values

### ISSUE THREAD

**Issue by SteveSysadmin** [markusressel/fan2go#246]
My GPU temperature sensor is configured in fan2go.yaml like this:
```
sensors:
  - id: gpu_sensor
    cmd:
      exec: /usr/bin/nvidia-smi
      args: [ "--query-gpu=temperature.gpu", "--format=csv,noheader,nounits" ]
```
and I can query the sensor like this:

`fan2go sensor --id gpu_sensor`

The value is in 2 digit format, eg 35. Is this an acceptable input value? I noticed in "fan2go detect" the values are all 5 digits.

Please tell me if this is ok or not.
