### ISSUE TITLE
Fails to set PWM value automatically, even though it does this manually

### ISSUE THREAD

**Issue by mks-h** [markusressel/fan2go#264]
**Describe the bug**
When running fan2go as a daemon, it fails to set PWM value, reporting `WARNING  PWM of cpu_fan was changed by third party! Last set PWM value was: 255 but is now: 128`, and the speed doesn't change. Yet, it doesn't have issues changing it with `sudo /usr/local/bin/fan2go fan -i cpu_fan speed 255`.

Just to be clear, there is no third party controlling the fan, and I can control it manually just fine:
```
# cat /sys/class/hwmon/hwmon3/pwm1 
255
# echo 128 > /sys/class/hwmon/hwmon3/pwm1 
# cat /sys/class/hwmon/hwmon3/pwm1 
128
```

**Desktop (please complete the following information):**

- Distro: OpenSUSE MicroOS (Tumbleweed base)
- `uname -a`: `Linux Vostro 6.5.6-1-default #1 SMP PREEMPT_DYNAMIC Fri Oct  6 11:20:48 UTC 2023 (c97c2df) x86_64 x86_64 x86_64 GNU/Linux`
- `sensors -v`: sensors version 3.6.0 with libsensors version 3.6.0
- `fan2go version`: 0.8.1 (compiled from 17451b6afa59752a1519931b8cc54de8d28a7e00)

**Additional context**
<details>
<summary>Config</summary>

```
dbPath: "/etc/fan2go/fan2go.db"

fans:
  - id: cpu_fan
    hwmon:
      platform: dell_smm-isa-0000
      rpmChannel: 1
      pwmChannel: 1
    neverStop: true
    curve: cpu_curve
    minPwm: 128
    startPwm: 128
    maxPwm: 255
    pwmMap:
      0: 0
      64: 128
      128: 255

sensors:
  - id: sensor1
    hwmon:
      platform: dell_smm-isa-0000
      index: 1
  - id: sensor2
    hwmon:
      platform: dell_smm-isa-0000
      index: 2
  - id: sensor3
    hwmon:
      platform: dell_smm-isa-0000
      index: 3

curves:
  - id: cpu_curve
    function:
      type: maximum
      curves:
        - curve1
        - curve2
        - curve3
  - id: curve1
    linear:
      sensor: sensor1
  - id: curve2
    linear:
      sensor: sensor2
  - id: curve3
    linear:
      sensor: sensor3

statistics:
  enabled: false

api:
  enabled: false

profiling:
  enabled: false
```

</details>
