### ISSUE TITLE
Inappropriately using the bug tracker to figure out a configuration issue that I am having and not understanding how to fix it

### ISSUE THREAD

**Issue by thyTwilightGoth** [markusressel/fan2go#265]
Hi here is my fan2go.yaml config:

```
fans:
    - id: CPU
      cmd:
        setPwm:
          exec: /usr/bin/nbfc
          args: ["set", "-f", "0", "-s", "%pwm%"]

        getRpm:
          exec: /usr/bin/cat
          args: ["/sys/devices/platform/asus-nb-wmi/hwmon/hwmon6/fan1_input"]

        minPwm: 12.5
        startPwm: 12.5
        maxPwm: 100

    - id: GPU
      cmd:
        setPwm:
          exec: /usr/bin/nbfc
          args: ["set", "-f", "1", "-s", "%pwm%"]

        getRpm:
          exec: /usr/bin/cat
          args: ["/sys/devices/platform/asus-nb-wmi/hwmon/hwmon6/fan2_input"]

        minPwm: 12.5
        startPwm: 12.5
        maxPwm: 100


sensors:
    - id: CPU_Temp
      hwmon:
        platform: k10temp-pci-00c3
        index: 1

    - id: GPU_Temp
      hwmon:
        platform: amdgpu-pci-0c00
        index: 1


curves:
    - id: CPU_Curve
      linear:
        sensor: CPU_Temp
        min: 40
        max: 80

    - id: GPU_Curve
      linear:
        sensor: GPU_Temp
        min: 40
        max: 80
```

And here is the output of ```doas fan2go config validate```

```
 INFO  Using configuration file at: /etc/fan2go/fan2go.yaml
 WARNING  Unused curve configuration: CPU_Curve
 WARNING  Unused curve configuration: GPU_Curve
 ERROR   Validation failed: fan CPU: missing curve definition in configuration entry
```

I am on arch linux

**Comment by jhillest** [comment]
Each sequence (fans, sensors, curves) are indented 4 spaces, but the key and value pairs are indented by 2 spaces.
The package `yamllint`, available in the extra repository, will complain of inconsistent use of indentation on your config.

**Comment by thyTwilightGoth** [comment]
Well, I got a different error when I the indentation in my config to this:

```
fans:
    - id: CPU
        cmd:
        setPwm:
            exec: /usr/bin/nbfc
            args: ["set", "-f", "0", "-s", "%pwm%"]

        getRpm:
            exec: /usr/bin/cat
            args: ["/sys/devices/platform/asus-nb-wmi/hwmon/hwmon6/fan1_input"]

        minPwm: 12.5
        startPwm: 12.5
        maxPwm: 100

    - id: GPU
        cmd:
        setPwm:
            exec: /usr/bin/nbfc
            args: ["set", "-f", "1", "-s", "%pwm%"]

        getRpm:
            exec: /usr/bin/cat
            args: ["/sys/devices/platform/asus-nb-wmi/hwmon/hwmon6/fan2_input"]

        minPwm: 12.5
        startPwm: 12.5
        maxPwm: 100


sensors:
    - id: CPU_Temp
        hwmon:
            platform: k10temp-pci-00c3
            index: 1

    - id: GPU_Temp
        hwmon:
            platform: amdgpu-pci-0c00
            index: 1


curves:
    - id: CPU_Curve
        linear:
            sensor: CPU_Temp
            min: 40
            max: 80

    - id: GPU_Curve
        linear:
            sensor: GPU_Temp
            min: 40
            max: 80
```

The error now is:

```
  ERROR   Error sending notification: exit status 1
  FATAL   Error reading config file, While parsing config: yaml: line 3: mapping values are not allowed in this context
```

I don't know what I did wrong, but at least the error is different now T_T
