### ISSUE TITLE
Fan RPM doesn't follow linear steps fan curve   

### ISSUE THREAD

**Issue by dduits** [markusressel/fan2go#301]
**Describe the bug**
The actual RPM of a fan that is controlled by fan2go doesn't match the linear fan curve defined in `/etc/fan2go/fan2go.yaml`, the actual PWM value always seems to be a certain amount above the specified PWM value. For example, when specifying a linear fan curve with the following steps  `55 -> 60`, `60 -> 90`, `90 -> 255` (°C -> PWM) and having a sensor input temperature of 42.0 °C, fan2go will report `Setting Fan PWM of 'front_intake' to 81 ...` instead of a PWM value around `60`. This results in the actual fan RPM being higher and the fan making more noise than expected.  

**To Reproduce**

1. Define a linear fan curve with steps for a particular fan in `/etc/fan2go/fan2go.yaml`
```yaml
...
curves:
  - id: front_intake_curve
    linear:
      sensor: cpu_tctl
      steps:
        - 55: 60
        - 80: 90
        - 90: 255
```
2. Observe the fan RPM and sensor temperature specified for the fan curve. In my case `Tctl` (CPU temperature of my AMD Ryzen 9 5950X) with the following command: `watch -t -n0.5 'sensors | grep "fan*\|Tctl\|Tccd"'` 
3. Run fan2go with the verbose flag (`fan2go -v`) as root and observe the PWM DEBUG logs (e.g. `Setting Fan PWM of 'front_intake' to n`) 
4. Observe the fan2go setting the PWM ~20 points higher than the PWM specified value in the temperature/PWM value in `fan2go.yaml` 

**Expected behavior**
I expect fan2go to match the specified linear fan curve defined in `fan2go.yaml`. I.e. when `Tctl` reports a temperature lower than 55 °C fan2go send a PWM signal of `60` to the defined fan.

Here's a graph that illustrates what I'm trying to achieve with with the fan curve described above:

![fan_curve](https://github.com/user-attachments/assets/7662907e-6993-4bbd-b2c8-1765bccdee32)

**Screenshots**

[Screencast_20240715_190146.webm](https://github.com/user-attachments/assets/be2d31b2-dc61-45d2-a344-73c2b06692ad)

The DEBUG logs show the PWM value sticking at `82` PWM even though the `Tctl` is below the first step (55 °C -> 60 PWM) in the linear fan curve.

**Desktop (please complete the following information):**

- Distro: Arch Linux
- `uname -a`: `Linux jade 6.9.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 12 Jul 2024 00:06:53 +0000 x86_64 GNU/Linux`
- `sensors -v`: `sensors version 3.6.0+git with libsensors version 3.6.0+git`
- `fan2go version`: `0.8.1`

**Additional context**
## Minimal fan2go.yaml used to reproduce the bug
```yaml
fans:
  - id: front_intake
    hwmon:
      platform: nct6798-isa-0290
      rpmChannel: 3
    neverStop: true
    minPwm: 30
    startPwm: 30
    curve: front_intake_curve

sensors:
  - id: cpu_tctl
    hwmon:
      platform: k10temp-pci-00c3
      index: 1

curves:
  - id: front_intake_curve
    linear:
      sensor: cpu_tctl
      steps:
        - 55: 60
        - 80: 90
        - 90: 255
```
## Hardware
**Fan:** Noctua NF-A14 PWM chromax.Black.swap
**Motherboard:** ASUS ROG STRIX X570-E GAMING WIFI II
