### ISSUE TITLE
`getRpm` required when using `fan` `cmd`

### ISSUE THREAD

**Issue by diggit** [markusressel/fan2go#310]
**Describe the bug**
In readme, there is an example with cmd controlled fan and `getPwm` is marked as optional. I also found #265 where the `getPwm` is also omitted and it was not an error. my configuration does not define it, but validation complains

**To Reproduce**
``` yaml
fans:
  - id: main
    curve: cpu_curve
    cmd:
      setPwm:
        exec: /usr/bin/ectool
        args: [ "fanduty", "0", "%pwm%" ]

      # (optional) Command to retrieve the current PWM value (0..255)
      # getPwm:
      #   exec: /usr/bin/nvidia-settings
      #   args: [ "-a", "someargument" ]
      # # (optional) Command to retrieve the current RPM value
      getRpm:
        # wrapped ectool output because it returns "Fan 0 RPM: 1234" to get only "1234"
        exec: /usr/bin/wrap_ectool_getfanrpm
        args: []

    minPwm: 10
    startPwm: 15
    maxPwm: 10
```

Validation
```
fan2go config validate
INFO  Using configuration file at: /etc/fan2go/fan2go.yaml
ERROR   Validation failed: fan main: missing getPwm configuration
```

**Expected behavior**
Validation passes

**Desktop**

- Distro: Arch Linux
- `uname -a`: `Linux xlylt 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux`
- `sensors -v`: `sensors version 3.6.0+git with libsensors version 3.6.0+git`
- `fan2go version`: `0.8.1`
