### ISSUE TITLE
Unable to set up my fans, fan2go.yaml settings seem to be ignored

### ISSUE THREAD

**Issue by dinvlad** [markusressel/fan2go#324]
**Describe the bug**
I'm having trouble setting up my fan curves. I have set `minPwm`, `startPwm` and `maxPwm` for each fan, but fans are still getting initialized on every run, and the curve values don't appear to follow what I wanted.

**To Reproduce**

1. Run `sudo /nix/store/84601dyyp25hqbq9a49kplnj76ljh1ji-fan2go-0.9.0/bin/fan2go -c fan2go.yaml -v` (see the config below)
2. Observe fans being initialized, with a long stream of `Setting Fan PWM of ...`, then `Saving pwm map to fan...`, and finally `Measuring RPM of ...`
3. Observe a stream of `Evaluating curve` with `Desired PWM: 0`, despite temperature readings from sensors being noticeable above their `min` values.
4. Re-run (1) and observe the same behavior each time (actually, Measuring part does seem to be skipped on subsequent runs; but not Setting Fan PWM part, which still takes a while and results in undesirable "slow spin down" behavior at the start)

**Expected behavior**
1. Fans should not be initialized again on each run.
2. Fans' PWM should be set according to linear curves (or an average of them) between `min` and `max` temp readings, and the corresponding `minPwm` and `maxPwm` values.

**Screenshots**
My config:
```yaml
dbPath: /var/lib/fan2go/fan2go.db

sensors:
  - id: cpu_package
    hwmon:
      platform: coretemp
      index: 1

  - id: disk_0
    hwmon:
      platform: drivetemp-scsi-0-0
      index: 1

  - id: disk_4
    hwmon:
      platform: drivetemp-scsi-4-0
      index: 1

  - id: nvme_0
    hwmon:
      platform: nvme-pci-01.*
      index: 1

  - id: nvme_1
    hwmon:
      platform: nvme-pci-06.*
      index: 1

curves:
  - id: cpu
    linear:
      sensor: cpu_package
      min: 20000
      max: 80000

  - id: disk_0
    linear:
      sensor: disk_0
      min: 20000
      max: 60000

  - id: disk_4
    linear:
      sensor: disk_4
      min: 20000
      max: 60000

  - id: bay_0
    function:
      type: average
      curves:
      - disk_0

  - id: bay_1
    function:
      type: average
      curves:
      - disk_4

  - id: nvme_0
    linear:
      sensor: nvme_0
      min: 20000
      max: 70000

  - id: nvme_1
    linear:
      sensor: nvme_1
      min: 20000
      max: 70000

  - id: mobo
    function:
      type: average
      curves:
      - nvme_0
      - nvme_1

fans:
  - id: cpu
    hwmon:
      platform: quadro
      rpmChannel: 3
      pwmChannel: 3
    controlAlgorithm: direct
    neverStop: true
    curve: cpu
    minPwm: 33
    startPwm: 33
    maxPwm: 255

  - id: bay_0
    curve: bay_0
    hwmon:
      platform: quadro
      rpmChannel: 2
      pwmChannel: 2
    controlAlgorithm: direct
    neverStop: true
    minPwm: 90
    startPwm: 90
    maxPwm: 200

  - id: bay_1
    curve: bay_1
    hwmon:
      platform: quadro
      rpmChannel: 4
      pwmChannel: 4
    controlAlgorithm: direct
    neverStop: true
    minPwm: 90
    startPwm: 90
    maxPwdm: 200

  - id: mobo
    curve: mobo
    hwmon:
      platform: quadro
      rpmChannel: 1
      pwmChannel: 1
    controlAlgorithm: direct
    neverStop: true
    minPwm: 25
    startPwm: 25
    maxPwm: 255
```

Here's what the log said after the (very long) initialization (which happens on each run):
```
  DEBUG   Evaluating curve 'cpu'. Sensor 'cpu_package' temp '32°'. Desired PWM: 0
  DEBUG   Evaluating curve 'nvme_0'. Sensor 'nvme_0' temp '35°'. Desired PWM: 0
  DEBUG   Evaluating curve 'nvme_1'. Sensor 'nvme_1' temp '35°'. Desired PWM: 0
  DEBUG   Evaluating curve 'disk_4'. Sensor 'disk_4' temp '22°'. Desired PWM: 0
  DEBUG   Evaluating curve 'disk_0'. Sensor 'disk_0' temp '23°'. Desired PWM: 0
``` 

And here's what `fan2go detect` showed around that same time:
```
> jc42
  Sensors  Index  Label                       Value
           1      hwmon6/temp1 (temp1_input)  30500

> drivetemp-scsi-4-0
  Sensors  Index  Label                       Value
           1      hwmon4/temp1 (temp1_input)  22000

> coretemp-isa-0000
  Sensors  Index  Label                       Value
           1      Package id 0 (temp1_input)  31000
           2      Core 0 (temp2_input)        25000
           3      Core 4 (temp6_input)        28000
           4      Core 8 (temp10_input)       26000
           5      Core 12 (temp14_input)      30000
           6      Core 16 (temp18_input)      28000
           7      Core 20 (temp22_input)      28000
           8      Core 24 (temp26_input)      29000
           9      Core 25 (temp27_input)      29000
           10     Core 26 (temp28_input)      28000
           11     Core 27 (temp29_input)      28000
           12     Core 28 (temp30_input)      27000
           13     Core 29 (temp31_input)      27000
           14     Core 30 (temp32_input)      27000
           15     Core 31 (temp33_input)      27000

> nvme-pci-0100
  Sensors  Index  Label                    Value
           1      Composite (temp1_input)  35850

> quadro-hid-3-6
  Fans     Index  Channel  Label              RPM  PWM  Auto 
           1      1        Fan 1 speed        327  25   false
           2      2        Fan 2 speed        577  90   false
           3      3        Fan 3 speed        400  33   false
           4      4        Fan 4 speed        588  90   false
           5      5        Flow speed [dL/h]  0    N/A  false
  Sensors  Index  Label                             Value
           1      Sensor 1 (temp1_input)            N/A  
           2      Sensor 2 (temp2_input)            N/A  
           3      Sensor 3 (temp3_input)            N/A  
           4      Sensor 4 (temp4_input)            N/A  
           5      Virtual sensor 1 (temp5_input)    N/A  
           6      Virtual sensor 2 (temp6_input)    N/A  
           7      Virtual sensor 3 (temp7_input)    N/A  
           8      Virtual sensor 4 (temp8_input)    N/A  
           9      Virtual sensor 5 (temp9_input)    N/A  
           10     Virtual sensor 6 (temp10_input)   N/A  
           11     Virtual sensor 7 (temp11_input)   N/A  
           12     Virtual sensor 8 (temp12_input)   N/A  
           13     Virtual sensor 9 (temp13_input)   N/A  
           14     Virtual sensor 10 (temp14_input)  N/A  
           15     Virtual sensor 11 (temp15_input)  N/A  
           16     Virtual sensor 12 (temp16_input)  N/A  
           17     Virtual sensor 13 (temp17_input)  N/A  
           18     Virtual sensor 14 (temp18_input)  N/A  
           19     Virtual sensor 15 (temp19_input)  N/A  
           20     Virtual sensor 16 (temp20_input)  N/A  

> jc42
  Sensors  Index  Label                       Value
           1      hwmon5/temp1 (temp1_input)  31500

> drivetemp-scsi-0-0
  Sensors  Index  Label                       Value
           1      hwmon3/temp1 (temp1_input)  23000

> nvme-pci-06f00
  Sensors  Index  Label                    Value
           1      Composite (temp1_input)  34850
```

And here are also the fan curves:
```
cpu
                
  Min PWM    33 
  Start PWM  33 
  Max PWM    255

 2550 ┤                                                                                              ╭────
 2380 ┤                                                                                     ╭────────╯
 2210 ┤                                                                            ╭────────╯
 2040 ┤                                                                   ╭────────╯
 1870 ┤                                                            ╭──────╯
 1700 ┤                                                     ╭──────╯
 1530 ┤ ╭─╮                                         ╭───────╯
 1360 ┤╭╯ ╰──╮                                 ╭────╯
 1190 ┤│     │                         ╭───────╯
 1020 ┤│     │                     ╭───╯
  850 ┤│     │                 ╭───╯
  680 ┤│     │            ╭────╯
  510 ┤│     ╰╮      ╭────╯
  340 ┤│      ╰──────╯
  170 ┤│
    0 ┼╯
                                                    RPM / PWM

bay_0
                
  Min PWM    90 
  Start PWM  90 
  Max PWM    200

 1404 ┤                                                                         ╭─────────────────────────
 1310 ┤                                                                     ╭───╯
 1217 ┤                                                                 ╭───╯
 1123 ┤                                                             ╭───╯
 1030 ┤                                                       ╭─────╯
  936 ┤                                                      ╭╯
  842 ┤                                                  ╭───╯
  749 ┤                                               ╭──╯
  655 ┤╭╮                                       ╭─────╯
  562 ┤│╰───────────────────────────────────────╯
  468 ┤│
  374 ┤│
  281 ┤│
  187 ┤│
   94 ┤│
    0 ┼╯
                                                    RPM / PWM

bay_1
                
  Min PWM    90 
  Start PWM  90 
  Max PWM    232

 1412 ┤                                                                          ╭────────────────────────
 1318 ┤                                                                      ╭───╯
 1224 ┤                                                                  ╭───╯
 1130 ┤                                                              ╭───╯
 1035 ┤                                                         ╭────╯
  941 ┤                                                       ╭─╯
  847 ┤                                                    ╭──╯
  753 ┤                                                ╭───╯
  659 ┤╭╮                                       ╭──────╯
  565 ┤│╰───────────────────────────────────────╯
  471 ┤│
  377 ┤│
  282 ┤│
  188 ┤│
   94 ┤│
    0 ┼╯
                                                    RPM / PWM

mobo
                
  Min PWM    25 
  Start PWM  25 
  Max PWM    255

 5145 ┤                                                                                               ╭───
 4802 ┤                                                                                         ╭─────╯
 4459 ┤                                                                                  ╭──────╯
 4116 ┤                                                                         ╭────────╯
 3773 ┤                                                                   ╭─────╯
 3430 ┤                                                             ╭─────╯
 3087 ┤╭╮                                                    ╭──────╯
 2744 ┤││                                              ╭─────╯
 2401 ┤││ ╭╮                                    ╭──────╯
 2058 ┤││ ││                               ╭────╯
 1715 ┤││╭╯│                        ╭──────╯
 1372 ┤│││ │                   ╭────╯
 1029 ┤│││ │             ╭─────╯
  686 ┤│││ │         ╭───╯
  343 ┤│╰╯ ╰─────────╯
    0 ┼╯
                                                    RPM / PWM
```

**Desktop (please complete the following information):**

- Distro: NixOS 24.05
- `uname -a`: `Linux homelab 6.11.3 #1-NixOS SMP PREEMPT_DYNAMIC Thu Oct 10 10:04:18 UTC 2024 x86_64 GNU/Linux`
- `sensors -v`: `sensors version 3.6.0 with libsensors version 3.6.0`
- `fan2go version`: `dev` (NixOS "unstable" version tag `0.9.0`)

**Additional context**
I've tried various settings, setting the `steps:` or sensor readings in degrees rather than milli-degrees. But nothing seems to matter - either I get fans set to 255, or 0.. And initialization takes a while each time.
