### ISSUE TITLE
maxPwmChangePerCycle buggy, keeps fan off

### ISSUE THREAD

**Issue by jwefers** [markusressel/fan2go#326]
Thanks for picking up my PR and making the direct algo happen. I think i dis

**Describe the bug**
when using controlAlgorithm.direct.maxPwmChangePerCycle with any value, it wants to set the correct pwm value, but then sets the fan speed to zero instead.

As last time, i'll try to properly debug this when i find time, but right now, Stalker 2 was more important.

**To Reproduce**

config:
```yaml
fans:
  - id: myfan
    hwmon:
      platform: nct6792-isa-0290
      rpmChannel: 3
      pwmChannel: 3
    neverStop: true
    curve: topfans_curve
    controlAlgorithm:
        direct:
            maxPwmChangePerCycle: 10
    pwmMap:
      0: 0
      255: 255
```
I assume curve and sensor do not matter, use anything.

What happens is, Debug shows correct desired PWM, but actually set PWM is zero and fan stays off.
When just using direct without maxPwmChangePerCycle, it works as expected.

**Expected behavior**
As temp in curves are changing, target PWM is slowly approached

**Screenshots**

**Desktop (please complete the following information):**

- Distro: Arch
- `uname -a`: Linux xxx 6.11.9-arch1-1 1 SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:06:17 +0000 x86_64 GNU/Linux
- `sensors -v`:  sensors version 3.6.0+git with libsensors version 3.6.0+git
- `fan2go version`: 0.9.0
