### ISSUE TITLE
Getting inaccurate PWM changed warnings

### ISSUE THREAD

**Issue by neonmoe** [markusressel/fan2go#378]
**Describe the bug**
Fan2go keeps warning about my fans being changed by a third party, but apparently expects something else than what it set?

> WARNING: PWM of rear_exhaust was changed by third party! Last set PWM value was '70', expected reported pwm '153' but was '70'

Shouldn't it be 70 if the last set PWM value was 70? Why would it be 153?

Could just be a confusing log, but if that's the case, I do wonder what the third party is, I have no idea what else could be changing the values.

**To Reproduce**

1. Start up fan2go.
2. Observe the log of endless warnings.

**Expected behavior**
No warnings, or at least warnings about actual problematic situations.

**Screenshots**
N/A.

**Desktop (please complete the following information):**

- Distro: Arch Linux
- `uname -a`: `Linux numakuro 6.14.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 29 May 2025 21:42:15 +0000 x86_64 GNU/Linux`
- `sensors -v`: `sensors version 3.6.2 with libsensors version 3.6.2`
- `fan2go version`: `0.9.2` reported by `fan2go version`, on commit 3b935ccfda70d9b2f0a4925abfb08aaf771d542a

**Additional context**

The error of course only appears if pwmValueChangedByThirdParty is actually enabled, which is disabled below because I wanted to get rid of the warnings, but nevertheless, my config:

<details><summary>My fan2go.yaml</summary>

```yaml
fans:
  - id: cpu_aio_exhaust
    hwmon:
      platform: nct6687-isa-0a20
      index: 2
    neverStop: true
    curve: cpu_curve
    minPwm: 90
    startPwm: 90
    maxPwm: 150
    pwmMap:
      90: 90
      110: 110
      150: 150
    sanityCheck:
      pwmValueChangedByThirdParty:
        enabled: false
  - id: front_top_intake
    hwmon:
      platform: nct6687-isa-0a20
      index: 3
    neverStop: true
    curve: cpu_curve
    minPwm: 90
    startPwm: 130
    maxPwm: 180
    pwmMap:
      90: 90
      130: 130
      180: 180
    sanityCheck:
      pwmValueChangedByThirdParty:
        enabled: false
  - id: front_bottom_intake
    hwmon:
      platform: nct6687-isa-0a20
      index: 4
    neverStop: true
    curve: gpu_curve
    minPwm: 90
    startPwm: 130
    maxPwm: 180
    pwmMap:
      90: 90
      130: 130
      180: 180
    sanityCheck:
      pwmValueChangedByThirdParty:
        enabled: false
  - id: rear_exhaust
    hwmon:
      platform: nct6687-isa-0a20
      index: 8
    neverStop: true
    curve: system_curve
    minPwm: 70
    startPwm: 130
    maxPwm: 180
    pwmMap:
      70: 70
      130: 130
      180: 180
    sanityCheck:
      pwmValueChangedByThirdParty:
        enabled: false
  - id: gpu_fan
    hwmon:
      platform: amdgpu-pci-02d00
      index: 1
    neverStop: true
    curve: gpu_curve
    maxPwm: 120
    sanityCheck:
      pwmValueChangedByThirdParty:
        enabled: false
sensors:
  - id: cpu_temp
    hwmon:
      platform: k10temp-pci-00c3
      index: 1
  - id: gpu_temp
    hwmon:
      platform: amdgpu-pci-02d00
      index: 1
  - id: system_temp
    hwmon:
      platform: nct6687-isa-0a20
      index: 2
curves:
  - id: cpu_curve
    linear:
      sensor: cpu_temp
      min: 60
      max: 100
  - id: gpu_curve
    linear:
      sensor: gpu_temp
      min: 40
      max: 100
  - id: system_curve
    linear:
      sensor: system_temp
      min: 30
      max: 90
```

</details>

Maybe the pwmMaps have something to do with it? Notably, gpu_fan, which doesn't have a pwmMap, does not report these warnings, all the other fans do. However, if I take out the pwmMaps, the fans just spin up to 255 and never move from there. And then it does appropriately warn me that `WARNING: PWM of cpu_aio_exhaust was changed by third party! Last set PWM value was '90', expected reported pwm '75' but was '255'`.
