### ISSUE TITLE
Why are there two "channel" config options, `detect` only displays one?

### ISSUE THREAD

**Issue by markusressel** [markusressel/fan2go#384]
HwMon fan examples (in the README and fan2go.yaml) contain
  ```yaml
      # The channel of this fan's RPM sensor as displayed by `fan2go detect`
      rpmChannel: 1
      # The pwm channel that controls this fan; fan2go defaults to same channel number as fan RPM
      pwmChannel: 1
  ```
  But the `fan2go detect` output has an `Index` and a `Channel` row. Is `Channel` the RPM or PWM channel? Is `Index` the other one or something different or not represented in the config at all?
