### ISSUE TITLE
What is a "cycle" in fan2go?

### ISSUE THREAD

**Issue by markusressel** [markusressel/fan2go#386]
The `controlAlgorithm:` section of the `cpu` fan has this:
  ```yaml
      direct:
        # together with maxPwmChangePerCycle, fan speeds will approach target value
        # with the given max speed.
        maxPwmChangePerCycle: 10
  ```
  What does "cycle" mean here?
